version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: ./build/package/dev/server.dockerfile
    env_file: ./configs/server.env
    depends_on:
      - mysql
    image: server-sample-img
    container_name: server-sample-cont
    ports:
      - 8080:8080
    volumes:
      - .:/go-crud-sample

  mysql:
    build:
      context: .
      dockerfile: ./build/package/dev/mysql.dockerfile
    env_file: ./configs/mysql.env
    image: mysql-sample-img
    container_name: mysql-sample-cont
    ports:
      - 3306:3306
    volumes:
      - mysql-vol:/var/lib/mysql
      - ./configs/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./db/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./db/mysql/log:/var/log

volumes:
  mysql-vol:
